### ISSUE TITLE
Discussion on how to support easy installation

### ISSUE THREAD

**Issue by ControlCplusControlV** [yacineMTB/talk#15]
Current CUBLAS is asked via prompt in the [build.sh](https://github.com/yacineMTB/talk/blob/master/build.sh#L43) script, but the command should instead grep `lspci` output, or check if its a aarch64 vs x86 and automatically enable the flag only if a CUDA capable device is detected

**Comment by yacineMTB** [comment]
I really appreciate you opening this task! This is _really_ worthwhile doing. Making it super simple & easy to set things up and running through a bash script is how this thing takes off.

Going to change the topic here about a discussion: what's the best way to get people up and running?

I'm wary about adding complexity & automation build, and instead, would prefer to let people figure out _how_ to run it with different options. Really, we should instruct users to set up each individual interface, and a test script that they can run. This will help users know where to look for what flags they should use for their set up.

I think this is more of a question of what kind of users we're targeting: what level of sophistication they need
We're at extremely early stages, which means we will break the "interface" so to speak. So maybe, showing people how, but not hand holding them to intentionally filter out non power-users is good to start with.

**Comment by ControlCplusControlV** [comment]
A good filter then might be something like a `model-compose.yaml`, which could provide a base configuration, but in an accessible way that encourages people to tinker, such as

```yaml
models:
  - name: llama
    type: chat_output
    config:
      model_path: /path/to/llama_model.pt
      cuda: yes

  - name: whisper
    type: chat_input
    config:
      model_path: /path/to/whisper_model.pt
      cuda: no
```

Providing something like this provides an interface which is easy to upgrade and tinker with, and allows easy additions in the futures (for ex: adding in your own QLoRa on LLaMa, or a Stable-Diffusion fork for a portrait output for your digital companion). It also allows for individual flag tweaking per model. I also think this strikes a good balance between "automagical" installation and configuration, and individual tinkering and tweaking. (Yes this is a sly way to propose changing config.json)
